jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      node_js: 8
      script:
        - npm run jsonlint
        - npm run svglint
        - npm run wslint
    - name: "Build website"
      language: ruby
      rvm: 2.4.1
      install:
        - gem install jekyll
      script:
        - jekyll build
    - name: "Test package"
      language: node_js
      node_js: 8
      script:
        - npm run test

    - stage: deploy
      name: "Git tag"
      language: node_js
      node_js: 8
      if: branch = master

      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "YOUR GIT USER NAME"
        - git config --local user.email "YOUR GIT USER EMAIL"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: "$GITHUB_KEY"
        skip_cleanup: true
    - name: "NPM Package"
      language: node_js
      node_js: 8
      if: branch = master

      deploy:
        provider: npm
        skip_cleanup: true
        email: "johanringmann@gmail.com"
        api_key: "$NPM_KEY"
        on:
          branch: master

notifications:
  email:
    on_success: never
    on_failure: change
