jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      node_js: 8
      script:
        - npm run jsonlint
        - npm run svglint
        - npm run wslint
    - name: "Build website"
      language: ruby
      rvm: 2.4.1
      install:
        - gem install jekyll
      script:
        - jekyll build
    - name: "Test package"
      language: node_js
      node_js: 8
      script:
        - npm run test

    - stage: deploy
      name: "Simple Icons Font"
      language: node_js
      node_js: 8
      if: branch = develop

      install:
        - npm install
      script:
        - mkdir _site
        - touch _site/index.html

      deploy:
        local-dir: ./_site
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        on:
          branch: develop

notifications:
  email:
    on_success: never
    on_failure: change
