jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      node_js: 8
      script:
        - npm run jsonlint
        - npm run svglint
        - npm run wslint
    - name: "Build website"
      language: ruby
      rvm: 2.4.1
      install:
        - gem install jekyll
      script:
        - jekyll build
    - name: "Test package"
      language: node_js
      node_js: 8
      script:
        - npm run test

    - stage: Test deploy
      name: Test extract version from package.json
      language: node_js
      node_js: 8
      script:
        - git config --local user.name "Example name"
        - git config --local user.email "name@example.com"
        - export PACKAGE_VERSION=$(cat package.json | grep 'version' | sed 's/[ \",:]//g' | sed 's/version//')
        - echo "The current version of the package is $VERSION, creating tag for that"
        - git tag $PACKAGE_VERSION

    - stage: deploy
      name: "Git tag"
      language: node_js
      node_js: 8
      if: branch = master

      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "$GITHUB_USERNAME"
        - git config --local user.email "$GITHUB_EMAIL"
        - export PACKAGE_VERSION=$(cat package.json | grep 'version' | sed 's/[ \",:]//g' | sed 's/version//')
        - git tag $PACKAGE_VERSION
      deploy:
        provider: releases
        api_key: "$GITHUB_KEY"
        skip_cleanup: true
    - name: "NPM Package"
      language: node_js
      node_js: 8
      if: branch = master

      deploy:
        provider: npm
        skip_cleanup: true
        email: "johanringmann@gmail.com"
        api_key: "$NPM_KEY"
        on:
          branch: master

notifications:
  email:
    on_success: never
    on_failure: change
