name: Publish
on:
  push:
    branches:
    - master

jobs:
  npm:
    name: NPM Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Sanity check
      run: |
        npm run lint
        npm run test
    - name: Deploy to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
  github:
    name: GitHub release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Sanity check
      run: |
        npm run lint
        npm run test
    - name: Get release message
      id: commit
      uses: kceb/git-message-action@v1
    - name: Create git tag
      id: create_tag
      run: |
        git config --local user.name ${{ secrets.GH_USERNAME }}
        git config --local user.email ${{ secrets.GH_EMAIL }}
        export PACKAGE_VERSION=$(cat package.json | grep 'version' | sed 's/[ \",:]//g' | sed 's/version//')
        git tag $PACKAGE_VERSION
        echo "::set-output name=tag::$PACKAGE_VERSION"
    - name: Push git tag
      uses: actions-ecosystem/action-push-tag@v1
      with:
        tag: ${{ steps.create_tag.outputs.tag }}
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: Release ${{ steps.create_tag.outputs.tag }}
        body: ${{ steps.commit.outputs.git-message }}
        draft: false
        prerelease: false
