name: Verify
on: [pull_request, push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: |
        npm run jsonlint
        npm run svglint
        npm run wslint
        npm run our-lint
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup cache for gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install Jekyll
      run: |
        echo -e 'source "https://rubygems.org"\n\ngem "jekyll"' > Gemfile
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Build website
      run: bundle exec jekyll build
  test:
    name: Test package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
